include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/.test_coverage.dart
    - coverage/**/*

  strong-mode:
    - implicit-casts: false
    - implicit-dynamic: false

  enable-experiment:
    - non-nullable
  
linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_positional_boolean_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_this
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - close_sinks
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - hash_and_equals
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - null_closures
    - only_throw_errors
    - package_api_docs
    - package_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - sort_child_properties_last
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks
    - use_key_in_widget_constructors
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks